//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class mycard
    {
        public int id { get; set; }
        public string mycard1 { get; set; }
        public Nullable<int> balance { get; set; }
    }
}
